### ISSUE TITLE
permission denied to create work tree dir

### ISSUE THREAD

**Issue by OdieArbuckle** [hissingshark/retrOSMCmk2#10]
Hi,

I'm having the below issue installing it on a Vero4k+.  How can I fix this? I've tried shutting down Kodi to avoid interference with the installer script. What directory should I grant permissions to?

![image](https://user-images.githubusercontent.com/60320609/104837856-b68ebf80-58b7-11eb-8f85-615af7a02186.png)

Thx!
Odie

**Comment by hissingshark** [comment]
You appear to be installing under `/etc`, which is where configuration files go.
You should be installing in `/home/osmc`

**Comment by OdieArbuckle** [comment]
@hissingshark, thanks, I'll give it a shot ;-)

**Comment by OdieArbuckle** [comment]
Nope, same issue:

![image](https://user-images.githubusercontent.com/60320609/105027420-03a59980-5a50-11eb-9503-be7e1681c20c.png)

**Comment by hissingshark** [comment]
I'm looking into it - starting with trying to reproduce the issue.
There are other issues at the moment, which are potentially related,

**Comment by hissingshark** [comment]
In your second attempt you seem to be user "root".
Did you `su root` or something?

The install instructions are were:
```
cd
git clone https://github.com/hissingshark/retrOSMCmk2.git
cd retrOSMCmk2
sudo ./setup.sh
```
So you'd be user "osmc" and the repo would have been cloned to the home directory.

**Comment by OdieArbuckle** [comment]
I've considered that too. I've tried both. First I tried using the regular osmc user but this didn't work either. Last I tried using root in that same folder but to no avail. Do you need a screenshot of it?

**Comment by hissingshark** [comment]
Sorry, I have been unable to reproduce the issue.  Given you started out doing things your own way, I suspect there is something more to the problem.

**Comment by OdieArbuckle** [comment]
I could resintall the Vero4K with osmc and try from a clean install?
I could then follow the the retropie procedure exactly as shown in the tutorial.
Can I enable debug logs after the clean install before starting retropie install? Which logs should I enable?

**Comment by hissingshark** [comment]
I think that's the only way for you to move forwards unfortunately.
There's no logging for the installer itself. I do all this installing and re-installing on my own system before I publish anything, so it should just work.

**Comment by OdieArbuckle** [comment]
No point in keeping this one open
