### ISSUE TITLE
No emulation video output for Amiberry 3.3 on Vero4k

### ISSUE THREAD

**Issue by brevilo** [hissingshark/retrOSMCmk2#11]
(continuing from the [OSMC](https://discourse.osmc.tv/t/how-to-retrosmcmk2-a-retropie-installer-on-the-vero4k/82357/137) forum)

Whenever I launch any game I get a black screen **but can** hear the game's audio. The Amiberry config GUI works as expected.

Notes:
- The are no errors in `amiberry.log`
- This only affects Amiberry
- All libretro cores I tried worked just fine.
- Reinstalling retrOSMCmk2 (or RetroPi) didn't help
- OSMC (stable) is up to date.

Disclaimer: I decided to submit the issue here first, instead of upstream, since the Vero4k uses custom builds for [SDL](https://github.com/hissingshark/RetroPie-Setup/blob/vero4k/scriptmodules/supplementary/sdl2.sh) and [Amiberry](https://github.com/hissingshark/RetroPie-Setup/blob/vero4k/scriptmodules/emulators/amiberry.sh). I also presume that upstream doesn't have access to a Vero4k to reproduce the issue.

Cheers

**Comment by hissingshark** [comment]
It seems to be an upstream issue. There’s something ongoing that has been reported for the RPi which sounds similar enough. They froze at v3.3 on RetroPie because of it. I’ve had to go back to v3.1.3.1 for the Vero4k.

**Comment by brevilo** [comment]
Thanks for the update.

> There’s something ongoing that has been reported for the RPi which sounds similar enough

Do you have a link to the upstream issue such that we can track it?

> I’ve had to go back to v3.1.3.1 for the Vero4k

Does that mean you released a workaround (downgrade) until the upstream issue got fixed? How to use/apply/install it?

Cheers!
