### ISSUE TITLE
Launcher addon incompatibility with Kodi 19 (Matrix)

### ISSUE THREAD

**Issue by irfus** [hissingshark/retrOSMCmk2#12]
The emulation-station launcher addon for Kodi currently fails to install on a dev-build of osmc with Kodi 19. Addon needs to be updated to work with python 3 for this to be resolved.

**Comment by hissingshark** [comment]
Yes, that's right. Python 3 will be mandatory going forward. I've already started for compatibility and made changes which I'm testing when I can.
This won't be released until Matrix is, to avoid breaking Leia installs.
