### ISSUE TITLE
Joycon not detected

### ISSUE THREAD

**Issue by anmorfe** [hissingshark/retrOSMCmk2#16]
I´m trying to install retropie inside OSMC using your script, and all goes well, but when i try to configure nintendo joycon I get an advice that says "No devices were found, Ensure device is on and try again". I have done with joycon in discover mode, 
I get another advice that says "Unable to find mixer elements".

Sorry about my poor english.

**Comment by hissingshark** [comment]
The comment  "Unable to find mixer elements" is a standard one from EmulationStation and can be ignored.
As for this "nintendo joycon", I don't know what that is.  I certainly don't use one I'm afraid.
