### ISSUE TITLE
GPG issues

### ISSUE THREAD

**Issue by eyeshield117** [hissingshark/retrOSMCmk2#20]
I have this issues with multiple package, don't understand why:

![image](https://user-images.githubusercontent.com/97692274/175831439-7797d629-7a56-4a5d-9673-a69683a0b767.png)

**Comment by eyeshield117** [comment]
@hissingshark can you have a look on that, I am on RPI3.

**Comment by hissingshark** [comment]
This has already been raised in the OSMC forum.
