### ISSUE TITLE
Failed signature check during core packages installation 

### ISSUE THREAD

**Issue by cvandeplas** [hissingshark/retrOSMCmk2#24]
Latest OSMC version on a Raspberry pi 4.
Failed signature check for many packages during step 3: basic install : It looks like the retropie GPG key is not known.

![image](https://github.com/hissingshark/retrOSMCmk2/assets/1073662/47015a70-8549-42e9-a56d-f3225e187a0f)

![image](https://github.com/hissingshark/retrOSMCmk2/assets/1073662/afacd870-03d8-4e92-9e81-f8cf3236e931)

From https://retropie.org.uk/forum/topic/28002/gpg-server-error-when-trying-to-update-retropie-packages/8 I did
```
$ sudo gpg --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys DC9D77FF8208FFC51D8F50CCF1B030906A3B0D31
gpg: key F1B030906A3B0D31: public key "RetroPie Project <retropieproject@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```
Re-ran install core packages/basic install and installation worked.

**Comment by hissingshark** [comment]
Already fixed from a slightly different angle, but thank you.  I commented on the PR.
