### ISSUE TITLE
RetroPI kodi addon appears in program add-ons and not in game addons

### ISSUE THREAD

**Issue by cvandeplas** [hissingshark/retrOSMCmk2#26]
The RetroPI kodi addon appears in program add-ons and not in game addons

Kodi 19.5, on latest OSMC on raspberry pi 4

**Comment by hissingshark** [comment]
Interesting point.  But for all my reading of the docs I've not been able to fathom how to flag this in the addon.

**Comment by hissingshark** [comment]
The desired behaviour doesn't seem to be documented.

I've just played with the `provides` tag in the addon XML file and tried "game". Seems to work.

**Comment by cvandeplas** [comment]
Cool, thanks !
